name: On PR

on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  actions: read
  checks: write
  contents: read
  id-token: write

jobs:
  build:
    name: Build module
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/jahia/jahia-docker-mvn-cache:11-jdk-noble-mvn-loaded
      credentials:
        username: ${{ secrets.GH_PACKAGES_USERNAME }}
        password: ${{ secrets.GH_PACKAGES_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: jahia/jahia-modules-action/build@v2
        with:
          mvn_settings_filepath: .github/maven.settings.xml
          nexus_username: ${{ secrets.NEXUS_USERNAME }}
          nexus_password: ${{ secrets.NEXUS_PASSWORD }}
          tests_module_type: disabled
